### PR TITLE
EFA-511 Remove trusted server setting from the app

### PR DESCRIPTION
**Pull request by ig-garcia**

### CODE REVIEW

**Review by Stereodark — APPROVED** [review]
I think the removal has been implemented correctly, the main question I still have is if we should commit this removal before providing an alternative. As I shared some clients will want to save back to the server the emails in clear when they uninstall the product, for one of our prospects this is even a mandatory requirement, I wonder if we should remove the logic to do so, or just disable the buttons for now and provide an alternative button to do the same. Otherwise when we will work on that story to implement a mechanism to save back upon uninstallation, we will likely have to re-write some of the code we removed now.

**Comment by ig-garcia** [comment]
> I think the removal has been implemented correctly, the main question I still have is if we should commit this removal before providing an alternative. As I shared some clients will want to save back to the server the emails in clear when they uninstall the product, for one of our prospects this is even a mandatory requirement, I wonder if we should remove the logic to do so, or just disable the buttons for now and provide an alternative button to do the same. Otherwise when we will work on that story to implement a mechanism to save back upon uninstallation, we will likely have to re-write some of the code we removed now.

Well the alternative is not actually an alternative per se, it would be a different functionality that is only performed once. But this needs probably a better delimitation, because we cannot run any operation when the app is being uninstalled. So users clicking on the button to back up the unencrypted messages on the server may mess up the app...

**Comment by ig-garcia** [comment]
So yes for the moment we can just hide the functionality and the new feature needs to be defined in scope, etc.

**Comment by ig-garcia** [comment]
> So yes for the moment we can just hide the functionality and the new feature needs to be defined in scope, etc.

I keep the original branch locally in  my machine and force-pushed a simpler version that just hides the MDM setting

**Pull request merged**
