### PR TITLE
EFA-483 Fix version format for non-exact git tags

### PR DESCRIPTION
**Pull request by ig-garcia**

### CODE REVIEW

**Review by Stereodark — APPROVED** [review]
It seems reasonable, we try to fix strange patterns in the version using a REGEX. It feels like a workaround, but if we didn't find the root cause why the version string contains weird stuff, it's ok to add the extra safety measure.

**Review by pzplanck — APPROVED** [review]

**Comment by ig-garcia** [comment]
> It seems reasonable, we try to fix strange patterns in the version using a REGEX. It feels like a workaround, but if we didn't find the root cause why the version string contains weird stuff, it's ok to add the extra safety measure.

We found the reason.
We are extracting the version from a gradle library which does git describe --tags
 what happens is that when in git we are not exactly on a tag (a version), then the output of git describe will be tag-commit or similar. This will happen on any branch that is not exactly the release (since only the release has the clean git tag).

**Review by pzplanck — APPROVED** [review]
It looks clean. Noted this parameter

**Review by Stereodark — APPROVED** [review]
Looks much better now, it's not a workaround anymore, I would merge!

**Pull request merged**
